[package]
name = "elf"
version = "0.1.0"
edition = "2021"

[dependencies]


[lints.rust]
missing_docs = "warn"

[lints.clippy]
missing_errors_doc = "warn"
missing_panics_doc = "warn"
missing_docs_in_private_items = "warn"

arithmetic_side_effects = "warn"

as_underscore = "warn"
